### ISSUE TITLE
Slides for video

### ISSUE THREAD

**Issue by javieragazmuri** [ConsiliumBots/cb-siblings#10]
La idea es hacer unas slides que podamos pasarle a un desarrollador para que genere un video corto explicativo sobre como funciona la postulación de hermanos y que explique los eventos de las cartillas (entre quizas otras cosas).

**Comment by tlarroucau** [comment]
Aquí quizás podemos linear unas Google slides y las vamos editando en conjunto. Podríamos partir con la explicación de lo que hace la postulacion de hermanos y un par de ejemplos

**Comment by javieragazmuri** [comment]
Esta es la [presentación](https://docs.google.com/presentation/d/1WdLYSuZOf-fKMyOLpJvLwi2MVAGDp0xK9ezekE4yK_8/edit?usp=sharing) que armé. Dejé algunas ideas.

**Comment by tlarroucau** [comment]
Bkn @javieragazmuri !

Un comentario por ahora. La parte donde dice: 

_"Ojo! Colegio al cual el mayor fue asignado debe estar entre las preferencias del menor para que la postulación familiar funcione."_

Eso salvo que sea `matricula asegurada` cierto? sera bueno ser explicito ahi en eso para que se consistente con lo que viene despues?

Tenemos ya definidos cuales son los eventos de las cartillas pa pensar en que ponemos en la slide?

@christopherneilson agregamos algo de explicacion de como funcionan las cosas dinamicas en el sistema tambien? 

Sera bueno @javieragazmuri partir el video explicando todas las formas en que el sistema trata de aumentar la probabilidad de que dos hermanos queden juntos? (como lo que tienes explicado en el documento de prioridades estaticas, etc.)

**Comment by javieragazmuri** [comment]
Actualicé la presentación. 

No creo que sume mucho explicar también la prioridad hermano (es muy conocida) ni el número aleatorio para hermanos del mismo nivel (muy complejo de explicar). Además, el video debe ser lo más corto posible para maximizar views.
